# Generated by Django 5.0.7 on 2024-07-20 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_firebaseuser_phone_number_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("logo", models.ImageField(upload_to="./media")),
                (
                    "game_type",
                    models.CharField(
                        choices=[("Premium", "Premium"), ("Free", "Free")],
                        default="Free",
                        max_length=255,
                    ),
                ),
            ],
        ),
    ]
