# Generated by Django 5.0.7 on 2024-07-20 08:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_match"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="endTime",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 7, 21, 14, 11, 59, 58369)
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="start_time",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
