# Generated by Django 5.0.7 on 2024-07-20 08:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_match_endtime_alter_match_start_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="endTime",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 7, 21, 14, 12, 33, 980426)
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="start_time",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 7, 20, 14, 12, 33, 980416)
            ),
        ),
    ]
