# Generated by Django 5.0.7 on 2024-08-31 15:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_alter_match_end_time_alter_match_start_time_wallet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="end_time",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 9, 1, 21, 12, 59, 741415)
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="start_time",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 8, 31, 21, 12, 59, 741405)
            ),
        ),
    ]
