# Generated by Django 5.0.7 on 2024-09-01 02:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_alter_match_end_time_alter_match_start_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="img",
            field=models.ImageField(default=None, upload_to="./media"),
        ),
        migrations.AlterField(
            model_name="match",
            name="end_time",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 9, 2, 8, 39, 46, 993421)
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="start_time",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 9, 1, 8, 39, 46, 993412)
            ),
        ),
    ]
