# Generated by Django 5.0.7 on 2024-09-01 02:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_coupon_img_alter_match_end_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="withdrawlrequest",
            name="status",
            field=models.CharField(default="pending", max_length=255),
        ),
        migrations.AlterField(
            model_name="match",
            name="end_time",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 9, 2, 8, 44, 9, 862287)
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="start_time",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 9, 1, 8, 44, 9, 862274)
            ),
        ),
    ]
