# Generated by Django 5.0.7 on 2024-09-01 04:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_withdrawlrequest_status_alter_match_end_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="match",
            name="end_time",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 9, 2, 10, 39, 57, 722888)
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="start_time",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 9, 1, 10, 39, 57, 722879)
            ),
        ),
    ]
